IdentiyApp/Controllers/NegocioController.cs
using Model;
using Model.ModelContext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;



namespace IdentiyApp.Controllers
{
    public class NegocioController : Controller
    {

        private negocio negocios = new negocio();
        //private AspNetUsers _AspNetUsers = new AspNetUsers();
        private contribuyentes cont = new contribuyentes();
        private meses _meses = new meses();
        private Mes_Pago _mes_pago = new Mes_Pago();
        private pagos _pagos = new pagos();

        private direccion_negocio _direccion = new direccion_negocio();
        private actividad _actividad = new actividad();
        private tributos _tributos = new tributos();
        private formatos _formatos = new formatos();
        // GET: Negocio
        public ActionResult Index(int id)
        {

             //if (id==0)
             //{
             //    return Redirect("~/home");
             //}else
             //{
                 return View(
                 id == 0 ? new contribuyentes()
                         : cont.Obtener(id)
             );
            // }
          
            
        }

        public ActionResult CrudNegocio(int Id=0)
        {

            ViewBag.ListarMes = _mes_pago.Listar_mes();
            ViewBag.ListarNegocio = negocios.Listar_Negocios();
            ViewBag.Listarmeses = _meses.Listar_meses();
            ViewBag.ListarUser = cont.Todo();
            ViewBag.ListerPagos = _pagos.Listar_pagos(Id);

            ViewBag.ListarFormatos = _formatos.Listar_Formato();
            ViewBag.Listar_Direccion = _direccion.Listar_Direccion();
            ViewBag.ListarTributos = _tributos.ListarTributos();
            ViewBag.ListarActividad = _actividad.Listar_Actividad();
            return View(
                Id > 0 ? negocios.Obtener(Id)
                :negocios
                );
         }


        public ActionResult NuevoNegocio(int Id=0)
        {
            ViewBag.ListarMes = _mes_pago.Listar_mes();
            ViewBag.ListarNegocio = negocios.Listar_Negocios();
            ViewBag.Listarmeses = _meses.Listar_meses();
            ViewBag.ListarUser = cont.Todo();
            ViewBag.ListerPagos = _pagos.Listar_pagos();

            return View(
                Id > 0 ? negocios.Obtener(Id)
                : negocios
                );
        }


        //Realizar Pagos
        public ActionResult Realizar_Pagos(int id_n=0)
        {

           
            ViewBag.ListarNegocio = negocios.Listar_Negocios(id_n);
            return View();
        }



        //Guardar Nuevo Negocio
        [HttpPost]
        public ActionResult Guardar(negocio model,int mat=0)
        {

            model.Guardar();
            return Redirect("~/Negocio/Index/"+model.id_cont_negocio);
        }

        //Guardar Pago

        public ActionResult Guardar_Pago(pagos model,negocio n)
        {
            
            model.Guardar_Pago();
            //string cadena = System.Web.HttpContext.Current.Request.Url.AbsoluteUri;
            
            ViewBag.Message = "Pago Realizado Con Exito";
            return RedirectToAction("About","Home");
            
        }



    }

}

IdentiyApp/Views/Negocio/Index.cshtml
@model Model.ModelContext.contribuyentes

@{
    ViewBag.Title = Model.nombre_c + " ";
    List<Model.ModelContext.negocio> negocio = ViewBag._negocio;
}

<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="~/">Inicio</a></li>
    <li class="breadcrumb-item active">@(Model.nombre_c + " ")</li>
</ol>

    @Html.ActionLink("Nuevo Tributo", "crudnegocio", new {param1=Model.id}, new { @class = "btn btn-success" })
    @Html.ActionLink("Editar", "contact", "Home", new { id=Model.id }, new { @class = "btn btn-warning" })
<div class="panel panel-default">
    <div class="panel-heading">Información personal</div>

    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>Nombre</dt>
            <dd>@Model.nombre_c</dd>
            <dt>Apellido</dt>
            <dd>@Model.apellido_c</dd>

        </dl>
    </div>
</div>

@if (Model.negocio.Count > 0)
{
    <div class="card">
        <div class="card-header">Negocios Matriculados</div>
        <table class="table">
            <thead class="thead-inverse">
                <tr>
                    <th>Nombre</th>
                    <th style="width:60px;">N° de Matricula</th>
                    <th style="width: 6%; text-align:right;"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var c in Model.negocio)
                {
                    if (c.id_cont_negocio == Model.id)
                    {
                        <tr>
                            <td>@Html.ActionLink(c.nombre_n, "crudnegocio", new { param1 = Model.id, id = c.id_n }, new { @class = "" })</td>

                            <td>@c.num_mat</td>

                           @* <td><a href="~/negocio/index/@c.id_n" class="btn btn-dark pull-right">Editar</a></td>*@
                        </tr>
                    }

                }
            </tbody>
        </table>
    </div>
}
else
{
    <p>No hay Tributos.</p>
}

IdentiyApp/Views/Negocio/NuevoNegocio.cshtml
@model Model.ModelContext.negocio
@{
    ViewBag.Title = "";

    List<Model.ModelContext.AspNetUsers> Users = ViewBag.ListarUser;
    List<Model.ModelContext.negocio> Listar_N = ViewBag.ListarNegocio;
    List<Model.ModelContext.Mes_Pago> ListarMes = ViewBag.ListarMes;
    List<Model.ModelContext.meses> Listarmeses = ViewBag.Listarmeses;
    List<Model.ModelContext.pagos> Listarpagos = ViewBag.ListerPagos;
}
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="~/">Negocio</a></li>
    <li class="breadcrumb-item active">@(Model.id_n > 0 ? Model.nombre_n : "Nuevo Registro")</li>
</ol>
<h2>Nuevo Negocio-</h2>
@using (Html.BeginForm("Guardar", "Negocio", FormMethod.Post, new { id = "frm-negocio" }))
{
    @Html.HiddenFor(x => x.id_n)
    <div class="panel panel-default">
        <div class="panel-heading"> Informacion del Negocio</div>
        <div class="panel-body">
            <div class="form-group">

                <label>Nombre: </label>
                @Html.TextBoxFor(x => x.nombre_n, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.nombre_n, null, new { @class = "label label-danger" })
            </div>
            <div class="form-group">

                <label>Numero de Matricula: </label>
                @Html.TextBoxFor(x => x.num_mat, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.num_mat, null, new { @class = "label label-danger" })
            </div>
        </div>


        <div class="form-group">
            <label>Seleccione un Contribuyente</label>
            <select class="form-control" name="Curso_id">
                @foreach (var c in Users)
                {
                    if (c.Id == Model.id_cont_negocio)
                    {
                        <option selected="selected" value="@c.Id">@(c.Name + " " + c.LastName) </option>
                    }
                    else
                    {
                        <option value="@c.Id">@(c.Name + " " + c.LastName)</option>
                    }


                }
            </select>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading"> Pagos Realizados</div>
        <div class="panel-body">

            <div class="list-group">
                @foreach (var c in Model.pagos)
                {
                    var tomado = false;
                    foreach (var item in Listar_N)
                    {
                        foreach (var item2 in ListarMes)
                        {
                            foreach (var item3 in Listarmeses)
                            {
                                if (c.id_negocio == item.id_n)
                                {
                                    if (c.id_pago == item2.id_pago_mes)
                                    {
                                        if (item2.id_mes_pago == item3.id_mes)
                                        {
                                            tomado = true;

                                            <h4 class="list-group-item-heading">@item3.Mes </h4>
                                                        <p class="list-group-item-text">@c.concepto</p>

                                        }

                                    }
                                }
                            }

                        }

                    }
                }




            </div>
        </div>
    </div>
    <input data-ajax="true" data-confirm="¿Esta seguro de guardar este registro?" class="btn btn-info" type="submit" value="Guardar" />

}

IdentiyApp/Views/Negocio/Realizar_Pagos.cshtml
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

@{
    ViewBag.Title = "";

    
    List<Model.ModelContext.negocio> Listar_N = ViewBag.ListarNegocio;
   

}
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="~/">Negocio</a></li>
    <li class="breadcrumb-item active">Nuevo Registro</li>
</ol>
<h2>Nuevo Negocio-</h2>
@using (Html.BeginForm("Guardar_Pago", "Negocio", FormMethod.Post, new { id = "frm-pago" }))
{
   
    <div class="panel panel-default">
        <div class="panel-heading"> Informacion del Negocio</div>
        <div class="panel-body">
            <div class="form-group">

                <label>Concepto: </label>
                <input type="text" class="form-control" placeholder="Concepto de Pago" required />
            </div>


            <div class="form-group">
                <label>Negocio</label>
                <select class="form-control" name="Negocio_id">
                    @foreach (var n in Listar_N)
                    {
                        //Fr4agmento para recibir el parametro enviado desde otra vista con ActionLink
                        int id_n = Convert.ToInt32(Request.QueryString["id_n"]);
                        /****/
                        if (n.id_n == id_n)
                        {
                            <option selected="selected" value="@n.id_n">@(n.nombre_n) </option>
                        }
                        else
                        {
                            <option value="@n.id_n">@(n.nombre_n) </option>
                        }





                    }
                </select>
            </div>


            <div class="form-group">

                <label>Fecha de Pago: </label>
               <input type="datetime"  id="MyDate" class="form-control" required />
            </div>

            <div class="form-group">
                <label>Colector</label>
                <select class="form-control" name="UserId">
                    <option selected value="@Common.CurrentUser.Get.UserId">@(Common.CurrentUser.Get.Name+" "+Common.CurrentUser.Get.LastName)</option>
                </select>
               
            </div>

        </div>


       


       



    </div>
   
    <input data-ajax="true" data-confirm="¿Esta seguro de guardar este registro?" class="btn btn-info" type="submit" value="Guardar" />

}

<script type="text/javascript">
    $(function () {
        $("#MyDate").datepicker();
    });
</script>